version: '2'
services:
    api:
        depends_on:
            - db
        build:
            context: .
            dockerfile: api.Dockerfile
    db:
        build:
            context: .
            dockerfile: db.Dockerfile
